global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '{{ telegram_bot_token }}'
        chat_id: '{{ telegram_chat_id }}'
        parse_mode: 'HTML'
